name: Build and deploy app

on:
    push:
        branches:
            - main


jobs:
    build-deploy:
        name: build and deply react app
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            
            - name: Install dependecies
              run: npm install
              
            - name: Run build
              run: npm run build

